language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release


jobs:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install git-lfs; git lfs install; fi

before_script:
  - git lfs pull

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .
  - ctest --output-on-failure -VV
  - cd -

before_deploy:
  - source ci/travis/create-deploy-tar-$TRAVIS_OS_NAME.sh

deploy:
  provider: releases
  file: build/out/*.gz
  overwrite: true
  cleanup: false
  api_key:
    secure: XpwlZS95BCuoAWVNgkwKXR3Mz+ttRSVgUGS+cK3k2WCwD5/nqlKtd7xVy+v8YdnQv4rGq3rpzlVAVvagWC9jtxttS4cn5BVroTyFndmwbSUnZBNCYdXQyqiiYqNLyNvZsl35+Y0lqHPnG8qnNSyKLXwFMNgTeHNlrB8J6OX4iOWA/NS5dOVZokzhk/8t85oK2FMrZFkPC79nN2RWYM4nwJJnopeN8GSOS/3moCM6hmb4mgFyjh+LeNkcZTCPGK8wJ5yA7ayEkD07OkgqlihjCAUF3549EvIZRA9ToO8rKxZL/u3L6R5OoP4ndHkgrrCHPa8QPksCRVpL3DqCC2KBaouafnrergZ98lf+SX4jA8XTeEJShibsiTydv6dreFtIbudPk0L+d90Xb9P771zjDJaP0pdeabb4AA/OYWZKjdRLIwgUN1z/52QUzu8RexXNwY2l5vmOD9CRqFabxcxHnUanLDw4dMBCaqytLrkSC4NLNnjHHco+TRdoPohWwvRNfI+6uqrb4ld1D2cRh0mNSpjKmO6nKSAmYdt/mC2HzXPVBevhncOa1G8vU//F88PQ7aZoSexIhqm4mmuGw9OSjhY/kIzugd64vBIgfFl1WX6lHaAk8tTf40dn6aFhcfow7jxPcnZ8zLENbtj/Y6/RismFwVF4pkNnu4UNbacnKBQ=
  on:
    tags: true
